CALL code --install-extension 2gua.rainbow-brackets
CALL code --install-extension akamud.vscode-theme-onedark
CALL code --install-extension akamud.vscode-theme-onelight
CALL code --install-extension alefragnani.Bookmarks
CALL code --install-extension alefragnani.project-manager
CALL code --install-extension alphabotsec.vscode-eclipse-keybindings
CALL code --install-extension angryobject.react-pure-to-class-vscode
CALL code --install-extension azemoh.one-monokai
CALL code --install-extension bradgashler.htmltagwrap
CALL code --install-extension castwide.solargraph
CALL code --install-extension christian-kohler.npm-intellisense
CALL code --install-extension christian-kohler.path-intellisense
CALL code --install-extension chrmarti.regex
CALL code --install-extension cometeer.spacemacs
CALL code --install-extension cssho.vscode-svgviewer
CALL code --install-extension ctrlplusb.white-italic
CALL code --install-extension DanielPintilei.Theme-Cake
CALL code --install-extension dbaeumer.vscode-eslint
CALL code --install-extension deerawan.vscode-faker
CALL code --install-extension disk0.win-classic-theme
CALL code --install-extension donjayamanne.githistory
CALL code --install-extension dracula-theme.theme-dracula
CALL code --install-extension dsznajder.es7-react-js-snippets
CALL code --install-extension eamodio.gitlens
CALL code --install-extension emmanuelbeziat.vscode-great-icons
CALL code --install-extension eppz.eppz-code
CALL code --install-extension Equinusocio.vsc-community-material-theme
CALL code --install-extension Equinusocio.vsc-material-theme
CALL code --install-extension equinusocio.vsc-material-theme-icons
CALL code --install-extension eryouhao.brackets-light-pro
CALL code --install-extension fcunhaneto.karry-color-theme
CALL code --install-extension felipe-mendes.slack-theme
CALL code --install-extension formulahendry.auto-rename-tag
CALL code --install-extension hbenl.vscode-test-explorer
CALL code --install-extension HookyQR.beautify
CALL code --install-extension idleberg.hopscotch
CALL code --install-extension jeff-hykin.code-eol
CALL code --install-extension johnpapa.winteriscoming
CALL code --install-extension jolaleye.horizon-theme-vscode
CALL code --install-extension liviuschera.noctis
CALL code --install-extension mariorodeghiero.vue-theme
CALL code --install-extension mrmlnc.vscode-less
CALL code --install-extension mrmlnc.vscode-scss
CALL code --install-extension ms-python.python
CALL code --install-extension ms-vsts.team
CALL code --install-extension msjsdiag.debugger-for-chrome
CALL code --install-extension msjsdiag.vscode-react-native
CALL code --install-extension msnilshartmann.blue-light
CALL code --install-extension naumovs.color-highlight
CALL code --install-extension obrejla.netbeans-light-theme
CALL code --install-extension onecrayon.theme-quietlight-vsc
CALL code --install-extension PKief.material-icon-theme
CALL code --install-extension pranaygp.vscode-css-peek
CALL code --install-extension rebornix.ruby
CALL code --install-extension roehling.eclipse-color-theme
CALL code --install-extension rokoroku.vscode-theme-darcula
CALL code --install-extension ruslanusmanov.kot-stream-theme
CALL code --install-extension sh4dow.theme-notepadplusplusremixed
CALL code --install-extension siegebell.prettify-symbols-mode
CALL code --install-extension smlombardi.slime
CALL code --install-extension smokeyjoe.marvelous-light
CALL code --install-extension TabNine.tabnine-vscode
CALL code --install-extension teabyii.ayu
CALL code --install-extension thenikso.github-plus-theme
CALL code --install-extension thomaspink.theme-github
CALL code --install-extension tinkertrain.theme-panda
CALL code --install-extension Tyriar.lorem-ipsum
CALL code --install-extension Tyriar.terminal-tabs
CALL code --install-extension vscode-icons-team.vscode-icons
CALL code --install-extension WallabyJs.quokka-vscode
CALL code --install-extension wayou.vscode-todo-highlight
CALL code --install-extension wingrunr21.vscode-ruby
CALL code --install-extension wix.vscode-import-cost
CALL code --install-extension xabikos.JavaScriptSnippets
CALL code --install-extension zhuangtongfa.material-theme
